
site_blog_home:
    path:      /
    defaults:  { _controller: SiteBlogBundle:Advert:index }
    
site_blog_view:
    path:      /advert/{id}
    defaults:  { _controller: SiteBlogBundle:Advert:view }
    
site_blog_add:
    path:      /add
    defaults:  { _controller: SiteBlogBundle:Advert:add }

site_blog_slug:
    path:      /{year}/{slug}.{format}
    defaults:  
        _controller: SiteBlogBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml
