
site_blog_home:
    path:      /{page}
    defaults:  
        _controller: SiteBlogBundle:Advert:index
        page:        1
    requirements:
        page: \d*

site_blog_view:
    path:      /advert/{id}
    defaults:  { _controller: SiteBlogBundle:Advert:view }
    requirements:
        page: \d+
    
site_blog_add:
    path:      /add
    defaults:  { _controller: SiteBlogBundle:Advert:add }

site_blog_edit:
    path:      /edit/{id}
    defaults:  { _controller: SiteBlogBundle:Advert:edit }
    requirements:
        id: \d+

site_blog_delete:
    path:      /delete/{id}
    defaults:  { _controller: SiteBlogBundle:Advert:delete }
    requirements:
        id: \d+
