<?php

namespace SiteBlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAdvertWithCategories(array $categoryNames)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.categories', 'c')->addSelect('c');
        $qb->where($qb->expr()->in('c.name', $categoryNames));

        return $qb->getQuery()->getResult();
    }

    public function getAdverts($page, $nbPerPage)
    {
        $qb = $this->createQueryBuilder('a')
                   ->leftJoin('a.image', 'i')
                   ->addSelect('i')
                   ->leftJoin('a.categories', 'c')
                   ->addSelect('c')
                   ->orderBy('a.date', 'DESC')
                   ->getQuery();

        $qb->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($qb, true);
    }

    public function getPublishedQueryBuilder()
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.published = :published')
            ->setParameter('published', true)
            ;
    }
}
